# -*- coding: utf-8 -*-
"""Akramov

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19i6tongBd2KIq0a9iiy25gLQErfJpodV
"""

def Akramov_hayvonot_dunyosi(belgi):
    if belgi == "Sher":
        return "Yovvoyi hayvon"
    elif belgi == "Mushuk":
        return "Uy hayvoni"
    elif belgi == "Ot":
        return "Uy hayvoni"
    elif belgi == "Qoplon":
        return "Yovvoyi hayvon"
    elif belgi == "Kiyik":
        return "Yovvoyi hayvoni"
    elif belgi == "It":
        return "Uy hayvoni"
    elif belgi == "Timsoh":
        return "Yovvoyi hayvon"
    elif belgi == "Ilon":
        return "Sudralib yuruvchi hayvon"
    elif belgi == "Bo'ri":
        return "Yovvoyi hayvon"
    elif belgi == "Quyon":
        return "Ham yovvoyi, ham uy hayvoni"
    elif belgi == "Fil":
        return "Yovvoyi hayvon"
    elif belgi == "Akula":
        return "Okean maxluqi"
    else:
        return "Ensiklopediyaga murojaat qiling"

belgi = input("Hayvon nomini kiriting: ")
natija = Akramov_hayvonot_dunyosi(belgi)
print(natija)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2

def Akramov_tashxisi(belgi):
    if belgi == "Isitma":
         return "Parasetamol"
    elif belgi == "Tish og'rig'i":
        return "Kupen"
    elif belgi == "Qorin og'rig'i":
        return "Levomitsin"
    elif belgi == "Magne v6 eritma":
        return "Lakto-Filtrum"
    elif belgi == "Gijja":
        return "Metronidazol"
    elif belgi=="Ko'z og'rig'i":
     return "Deksatobrom"
    elif belgi=="Tomoq og'rig'i":
     return "Anzibel"
    elif belgi=="Bel og'rig'i":
     return "Dyuklofenak"
    elif belgi=="Jigar og'rig'i":
     return "Karsil"
    elif belgi=="Yurak og'rig'i":
     return "valerianka"
    else:
        return "Shifokorga murojaat qiling"

belgi = input("Dori nomini kiriting: ")
natija = Akramov_tashxisi(belgi)
print(natija)

from google.colab.patches import cv2_imshow
import cv2

def Akramov_tashxisi(belgi):
    if belgi == "Isitma":
        rasm = cv2.imread("images.jfif")
        if rasm is not None:
            cv2_imshow(rasm)
        else:
            print("Rasm topilmadi.")
        return "Parasetamol"
    elif belgi == "Bosh og'rig'i":
        return "Ibuprofen"
    else:
        return "Shifokorga murojaat qiling"

belgi = input("Belgini kiriting: ")
natija = Akramov_tashxisi(belgi)
print(natija)